### ISSUE TITLE
Only download new clips

### ISSUE THREAD

**Issue by ghost** [R3turn-Dev/TwitchClipDumper#6]
Tool works great. Is there a way to make it download only new clips that I haven't downloaded yet? Or download clips only from a specific date range? Thanks!

**Comment by return0927** [comment]
Hi. thank you for using my tool and glad at the fact it worked very well : D
I'll add both date range feature and avoiding existing file feature as well.

**Comment by ghost** [comment]
You're the champ! Thank you :-)

**Comment by return0927** [comment]
Sorry for the late support. This gonna be fixed :D thank you for your attention.
